# Generated by Django 4.2.5 on 2023-10-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(default=0)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
