# Generated by Django 4.2.5 on 2023-10-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_first_name_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
    ]
